### PR TITLE
[ENH] create tour

### LINKED ISSUE #298: create tour
detecting if this is the first time user is logged in: https://community.auth0.com/t/redirect-to-onboarding-flow-after-sign-up-or-first-log-in/36689

### PR DESCRIPTION
**Pull request by jdkent**
closes #298

### CODE REVIEW

**Comment by nicoalee** [comment]
added headless testing with cypress, still need to integrate it into github actions

**Comment by nicoalee** [comment]
@jdkent before we merge this in, I need help adding a piece of code to the other auth0 tenants to get the login count

**Comment by jdkent** [comment]
sure thing, are you missing admin access to something or do you need some other kind of help?

**Comment by nicoalee** [comment]
> sure thing, are you missing admin access to something or do you need some other kind of help?

oops i realize that I actually have access to the staging and prod tenants so I dont need help, thanks!

**Pull request merged**
