### PR TITLE
chore: merge the frontend with the backend

### PR DESCRIPTION
**Pull request by nicoalee**
Merging in the frontend neurosynth react project with the neurostore backend to form one repo

### CODE REVIEW

**Comment by nicoalee** [comment]
- [ ] waiting for approval from @jdkent

**Comment by jdkent** [comment]
could you call the folder `neurosynth-frontend`? Or something similar, I will be creating a neurosynth backend as well and that will help differentiate the projects.

**Comment by nicoalee** [comment]
> could you call the folder `neurosynth-frontend`? Or something similar, I will be creating a neurosynth backend as well and that will help differentiate the projects.

ok will do

**Comment by jdkent** [comment]
LGTM! merging

**Pull request merged**
